baseURL = "https://popagandhi.com/"
languageCode = "en-us"
title = "Pop22"
theme = "hugo-ink"
themesDir ="themes"
paginate = 20
rssLimit = 10
copyright = "Popagandhi since 2000."

# Static Dir
staticDir = ["static"]

[params]
	subtitle = "Reinventing my personal blog"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Photo Diary"
url = "/photos"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/skinnylatte"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
